image: aergus/latex

beamer-build :
        stage : build
        script :
                - make
        artifacts:
                paths:
                        - "*.pdf"
                expire_in: 5 years
        tags:
                - docker
